import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, AreaChart, Area, ResponsiveContainer } from "recharts";
import { Heart, Activity, Battery, Shield, Phone, Upload, FileText } from "lucide-react";
import { useToast } from "@/components/ui/use-toast";
import { useState } from "react";
import { EmergencyMonitor } from "@/components/EmergencyMonitor";
import { PrescriptionUpload } from "@/components/PrescriptionUpload";
import { InsuranceUpload } from "@/components/InsuranceUpload";
import { ChatBox } from "@/components/ChatBox";

const healthData = [
  { time: "6:00", heartRate: 68, bloodPressure: 120, steps: 0 },
  { time: "9:00", heartRate: 72, bloodPressure: 118, steps: 2500 },
  { time: "12:00", heartRate: 78, bloodPressure: 125, steps: 5200 },
  { time: "15:00", heartRate: 75, bloodPressure: 122, steps: 7800 },
  { time: "18:00", heartRate: 70, bloodPressure: 119, steps: 9200 },
  { time: "21:00", heartRate: 65, bloodPressure: 115, steps: 10500 },
];

const medicationSchedule = [
  { name: "Lisinopril", time: "8:00 AM", dosage: "10mg", status: "taken" },
  { name: "Metformin", time: "12:00 PM", dosage: "500mg", status: "taken" },
  { name: "Aspirin", time: "6:00 PM", dosage: "81mg", status: "pending" },
  { name: "Vitamin D", time: "8:00 PM", dosage: "1000 IU", status: "pending" },
];

const recentActivities = [
  { activity: "Morning walk", duration: "30 min", time: "7:30 AM", calories: 150 },
  { activity: "Light exercise", duration: "15 min", time: "10:00 AM", calories: 80 },
  { activity: "Garden work", duration: "45 min", time: "4:00 PM", calories: 200 },
];

export const CustomerDashboard = () => {
  const { toast } = useToast();
  const [reportRequest, setReportRequest] = useState("");

  const handleReportSubmit = () => {
    if (!reportRequest.trim()) {
      toast({
        title: "Please enter your report request",
        description: "Add details about what you'd like in your medical report.",
        variant: "destructive",
      });
      return;
    }

    toast({
      title: "Report Request Submitted",
      description: "Your medical report will be generated by AI and verified by a medical doctor. It will be uploaded to your dashboard within 48 hours.",
    });

    setReportRequest("");
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-3xl font-bold text-foreground">My Health Dashboard</h1>
        <Badge variant="secondary">Customer Portal</Badge>
      </div>

      {/* Emergency Monitor - Always at top for customers */}
      <EmergencyMonitor />

      {/* Health Status Cards */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
        <Card className="p-6">
          <div className="flex items-center space-x-2">
            <Heart className="h-8 w-8 text-red-500" />
            <div>
              <p className="text-sm text-muted-foreground">Heart Rate</p>
              <p className="text-2xl font-bold text-foreground">72 BPM</p>
              <p className="text-sm text-green-600">Normal</p>
            </div>
          </div>
        </Card>

        <Card className="p-6">
          <div className="flex items-center space-x-2">
            <Activity className="h-8 w-8 text-primary" />
            <div>
              <p className="text-sm text-muted-foreground">Daily Steps</p>
              <p className="text-2xl font-bold text-foreground">10,500</p>
              <p className="text-sm text-green-600">Goal achieved!</p>
            </div>
          </div>
        </Card>

        <Card className="p-6">
          <div className="flex items-center space-x-2">
            <Battery className="h-8 w-8 text-secondary" />
            <div>
              <p className="text-sm text-muted-foreground">Device Battery</p>
              <p className="text-2xl font-bold text-foreground">78%</p>
              <p className="text-sm text-muted-foreground">Good level</p>
            </div>
          </div>
        </Card>

        <Card className="p-6">
          <div className="flex items-center space-x-2">
            <Shield className="h-8 w-8 text-green-600" />
            <div>
              <p className="text-sm text-muted-foreground">Health Status</p>
              <p className="text-2xl font-bold text-foreground">Good</p>
              <p className="text-sm text-green-600">All systems normal</p>
            </div>
          </div>
        </Card>
      </div>

     {/* Health Charts */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <Card className="p-6 bg-gradient-to-br from-red-50 to-pink-50 border-red-200">
          <h3 className="text-lg font-semibold mb-4 text-red-700">Today's Heart Rate</h3>
          <ResponsiveContainer width="100%" height={300}>
            <LineChart data={healthData}>
              <CartesianGrid strokeDasharray="3 3" stroke="#f1f5f9" />
              <XAxis dataKey="time" tick={{ fontSize: 12 }} />
              <YAxis tick={{ fontSize: 12 }} />
              <Tooltip 
                contentStyle={{
                  backgroundColor: 'white',
                  border: '1px solid #e2e8f0',
                  borderRadius: '8px',
                  boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)'
                }}
              />
              <Line 
                type="monotone" 
                dataKey="heartRate" 
                stroke="#dc2626" 
                strokeWidth={3}
                dot={{ fill: '#dc2626', r: 4 }}
                activeDot={{ r: 6, fill: '#dc2626' }}
              />
            </LineChart>
          </ResponsiveContainer>
        </Card>

        <Card className="p-6 bg-gradient-to-br from-blue-50 to-indigo-50 border-blue-200">
          <h3 className="text-lg font-semibold mb-4 text-blue-700">Daily Activity</h3>
          <ResponsiveContainer width="100%" height={300}>
            <AreaChart data={healthData}>
              <CartesianGrid strokeDasharray="3 3" stroke="#f1f5f9" />
              <XAxis dataKey="time" tick={{ fontSize: 12 }} />
              <YAxis tick={{ fontSize: 12 }} />
              <Tooltip 
                contentStyle={{
                  backgroundColor: 'white',
                  border: '1px solid #e2e8f0',
                  borderRadius: '8px',
                  boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)'
                }}
              />
              <Area 
                type="monotone" 
                dataKey="steps" 
                stroke="#2563eb" 
                fill="url(#blueGradient)"
                strokeWidth={2}
              />
              <defs>
                <linearGradient id="blueGradient" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="5%" stopColor="#3b82f6" stopOpacity={0.8}/>
                  <stop offset="95%" stopColor="#3b82f6" stopOpacity={0.1}/>
                </linearGradient>
              </defs>
            </AreaChart>
          </ResponsiveContainer>
        </Card>
      </div>

      

      {/* Report Generation */}
      <Card className="p-6">
        <h3 className="text-lg font-semibold mb-4 flex items-center">
          <FileText className="h-5 w-5 mr-2" />
          Generate Medical Report
        </h3>
        <div className="space-y-4">
          <Textarea
            placeholder="Describe what you'd like included in your medical report (e.g., recent symptoms, medication review, health summary)..."
            value={reportRequest}
            onChange={(e) => setReportRequest(e.target.value)}
            rows={4}
          />
          <Button onClick={handleReportSubmit} className="w-full">
            Submit Report Request
          </Button>
        </div>
      </Card>

      
      {/* Emergency Contacts */}
      <Card className="p-6">
        <h3 className="text-lg font-semibold mb-4 flex items-center">
          <Phone className="h-5 w-5 mr-2" />
          Emergency Contacts
        </h3>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div className="p-4 border border-border rounded-lg">
            <p className="font-medium text-foreground">Primary Contact</p>
            <p className="text-sm text-muted-foreground">Dr. Sarah Johnson</p>
            <p className="text-sm text-foreground">(555) 123-4567</p>
          </div>
          <div className="p-4 border border-border rounded-lg">
            <p className="font-medium text-foreground">Emergency Services</p>
            <p className="text-sm text-muted-foreground">Local Emergency</p>
            <p className="text-sm text-foreground">911</p>
          </div>
          <div className="p-4 border border-border rounded-lg">
            <p className="font-medium text-foreground">Family Contact</p>
            <p className="text-sm text-muted-foreground">John Smith (Son)</p>
            <p className="text-sm text-foreground">(555) 987-6543</p>
          </div>
        </div>
      </Card>

      {/* AI Chatbox */}
      <ChatBox />
    </div>
  );
};